In [2]:
import pandas as pd

In [3]:
airbnb = pd.read_csv('C:/Users/music/Desktop/airbnb_test_users.csv')
airbnb.head()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser
0,5uwns89zht,7/1/2014,2.014070e+13,NaN,FEMALE,35.0,facebook,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari
1,jtl0dijy2j,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari
2,xx0ulgorjt,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome
3,6c6puo6ix0,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,IE
4,czqhjk3yfe,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Safari

In [4]:
#What is the average age of those who use each web browser type?
airbnb.groupby('first_browser')['age'].mean()

first_browser
-unknown-             41.526894
AOL Explorer          60.000000
Android Browser       42.822148
Apple Mail            26.750000
BlackBerry Browser    34.600000
Chrome                34.591678
Chrome Mobile         45.199058
Chromium              28.833333
CometBird             30.000000
Firefox               37.748143
IBrowse               51.000000
IE                    42.463107
IE Mobile             32.312500
IceWeasel             18.000000
Iron                  35.200000
Maxthon               31.000000
Mobile Firefox        31.800000
Mobile Safari         35.098486
Nintendo Browser            NaN
Opera                 38.444444
Opera Mini                  NaN
Opera Mobile          37.000000
Pale Moon             37.000000
Safari                36.416121
SeaMonkey                   NaN
Silk                  38.120000
SiteKiosk             57.000000
Sogou Explorer        28.000000
UC Browser            28.000000
Yandex.Browser        38.500000
wOSBrowser                  NaN
Name: age, dtype: float64

In [5]:
#What is the total signup_flow for each device?
airbnb.groupby('signup_flow').sum()

             timestamp_first_active  date_first_booking       age
signup_flow
0                      8.328823e+17                 0.0  865316.0
8                      1.510555e+15                 0.0    1604.0
12                     3.856971e+16                 0.0   39212.0
14                     8.056360e+13                 0.0       0.0
21                     2.014090e+13                 0.0      23.0
23                     7.196308e+16                 0.0  106398.0
25                     3.056365e+17                 0.0  237073.0

In [6]:
#They need the country information from this dataset included in the airbnb_test_users file.
airbnb2 = pd.read_csv('C:/Users/music/Desktop/airbnb_sample_submission.csv')
airbnb2.head()

           id country
0  5uwns89zht     NDF
1  jtl0dijy2j     NDF
2  xx0ulgorjt     NDF
3  6c6puo6ix0     NDF
4  czqhjk3yfe     NDF

In [7]:
#They need the country information from this dataset included in the airbnb_test_users file.
airbnb3 = pd.merge(airbnb, airbnb2, on='id')
airbnb3.head()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country
0,5uwns89zht,7/1/2014,2.014070e+13,NaN,FEMALE,35.0,facebook,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF
1,jtl0dijy2j,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF
2,xx0ulgorjt,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome,NDF
3,6c6puo6ix0,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,IE,NDF
4,czqhjk3yfe,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Safari,NDF

In [8]:
#Add additional users to the test file from this dataset.
airbnb4 = pd.read_csv('C:/Users/music/Desktop/airbnb_users.csv')
airbnb4.head()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country_destination
0,gxn3p5htnn,6/28/2010,2.009030e+13,NaN,-unknown-,NaN,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,NDF
1,820tgsjxq7,5/25/2011,2.009050e+13,NaN,MALE,38.0,facebook,0,en,seo,google,untracked,Web,Mac Desktop,Chrome,NDF
2,4ft3gnwmtx,9/28/2010,2.009060e+13,8/2/2010,FEMALE,56.0,basic,3,en,direct,direct,untracked,Web,Windows Desktop,IE,US
3,bjjt8pjhuk,12/5/2011,2.009100e+13,9/8/2012,FEMALE,42.0,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox,other
4,87mebub9p4,9/14/2010,2.009120e+13,2/18/2010,-unknown-,41.0,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,US

In [10]:
#combining country and country destination columns
airbnb3.columns = ['id', 'date_account_created', 'timestamp_first_active',
       'date_first_booking', 'gender', 'age', 'signup_method', 'signup_flow',
       'language', 'affiliate_channel', 'affiliate_provider',
       'first_affiliate_tracked', 'signup_app', 'first_device_type',
       'first_browser', 'country_destination']

In [11]:
airbnb3.columns

Index(['id', 'date_account_created', 'timestamp_first_active',
       'date_first_booking', 'gender', 'age', 'signup_method', 'signup_flow',
       'language', 'affiliate_channel', 'affiliate_provider',
       'first_affiliate_tracked', 'signup_app', 'first_device_type',
       'first_browser', 'country_destination'],
      dtype='object')

In [12]:
#Add additional users to the test file from this dataset.
airbnb5 = pd.concat([airbnb3, airbnb4], ignore_index=True)
airbnb5.head()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country_destination
0,5uwns89zht,7/1/2014,2.014070e+13,NaN,FEMALE,35.0,facebook,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF
1,jtl0dijy2j,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF
2,xx0ulgorjt,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome,NDF
3,6c6puo6ix0,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,IE,NDF
4,czqhjk3yfe,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Safari,NDF

In [23]:
airbnb5.tail()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country,country_destination
275542,zxodksqpep,6/30/2014,2.014060e+13,NaN,MALE,32.0,basic,0,en,sem-brand,google,omg,Web,Mac Desktop,Safari,NaN,NDF
275543,mhewnxesx9,6/30/2014,2.014060e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome,NaN,NDF
275544,6o3arsjbb4,6/30/2014,2.014060e+13,NaN,-unknown-,32.0,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox,NaN,NDF
275545,jh95kwisub,6/30/2014,2.014060e+13,NaN,-unknown-,NaN,basic,25,en,other,other,tracked-other,iOS,iPhone,Mobile Safari,NaN,NDF
275546,nw9fwlyb5f,6/30/2014,2.014060e+13,NaN,-unknown-,NaN,basic,25,en,direct,direct,untracked,iOS,iPhone,-unknown-,NaN,NDF